2016-05-16 14:45:39,307 [Dummy-1:139807773492992] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:45:39,330 [Dummy-1:139807773492992] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:45:39,330 [Dummy-1:139807773492992] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:45:39,332 [Dummy-1:139807773492992] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:45:50,746 [Thread-2:139807695042304] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in "[{'None': None, 'False': False, 'True': True}, {'request': <WSGIRequest: GET '/'>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'INFO': 20, 'SUCCESS': 25, 'DEBUG': 10, 'ERROR': 40}, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7f278807fea0>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f2788035a60>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f27880315f8>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f27837cac18>}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-05-16 14:45:50,764 [Thread-2:139807695042304] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in "[{'None': None, 'False': False, 'True': True}, {'request': <WSGIRequest: GET '/'>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'INFO': 20, 'SUCCESS': 25, 'DEBUG': 10, 'ERROR': 40}, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7f278807fea0>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f2788035a60>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f27880315f8>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f27837cac18>}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-05-16 14:47:04,841 [Dummy-1:140701061723904] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:47:04,879 [Dummy-1:140701061723904] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:47:04,879 [Dummy-1:140701061723904] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:47:04,881 [Dummy-1:140701061723904] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:47:39,717 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:47:39,751 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:47:39,752 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:47:39,754 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:47:39,758 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); (params None)
2016-05-16 14:47:39,800 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.041) CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); args=None
2016-05-16 14:47:39,802 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_content_type'; args=['django_content_type']
2016-05-16 14:47:39,805 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` ADD CONSTRAINT `django_content_type_app_label_76bd3d3b_uniq` UNIQUE (`app_label`, `model`); (params [])
2016-05-16 14:47:39,849 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.044) ALTER TABLE `django_content_type` ADD CONSTRAINT `django_content_type_app_label_76bd3d3b_uniq` UNIQUE (`app_label`, `model`); args=[]
2016-05-16 14:47:39,850 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:39,854 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('contenttypes', '0001_initial', '2016-05-16 14:47:39.852193'); args=['contenttypes', '0001_initial', '2016-05-16 14:47:39.852193']
2016-05-16 14:47:39,866 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL); (params None)
2016-05-16 14:47:39,908 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.041) CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL); args=None
2016-05-16 14:47:39,909 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_permission'; args=['auth_permission']
2016-05-16 14:47:39,918 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); (params None)
2016-05-16 14:47:39,965 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.046) CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); args=None
2016-05-16 14:47:39,967 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group'; args=['auth_group']
2016-05-16 14:47:39,968 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL); (params None)
2016-05-16 14:47:40,009 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.041) CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL); args=None
2016-05-16 14:47:40,011 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group_permissions'; args=['auth_group_permissions']
2016-05-16 14:47:40,025 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime(6) NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime(6) NOT NULL); (params None)
2016-05-16 14:47:40,094 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.068) CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime(6) NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime(6) NOT NULL); args=None
2016-05-16 14:47:40,096 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_user'; args=['auth_user']
2016-05-16 14:47:40,098 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL); (params None)
2016-05-16 14:47:40,139 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.041) CREATE TABLE `auth_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL); args=None
2016-05-16 14:47:40,141 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_user_groups'; args=['auth_user_groups']
2016-05-16 14:47:40,143 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL); (params None)
2016-05-16 14:47:40,184 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.040) CREATE TABLE `auth_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL); args=None
2016-05-16 14:47:40,186 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_user_user_permissions'; args=['auth_user_user_permissions']
2016-05-16 14:47:40,186 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
2016-05-16 14:47:40,290 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.103) ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); args=[]
2016-05-16 14:47:40,291 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permission_content_type_id_01ab375a_uniq` UNIQUE (`content_type_id`, `codename`); (params [])
2016-05-16 14:47:40,375 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.084) ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permission_content_type_id_01ab375a_uniq` UNIQUE (`content_type_id`, `codename`); args=[]
2016-05-16 14:47:40,376 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
2016-05-16 14:47:40,478 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.101) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); args=[]
2016-05-16 14:47:40,479 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissi_permission_id_84c5c92e_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
2016-05-16 14:47:40,590 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.110) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissi_permission_id_84c5c92e_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); args=[]
2016-05-16 14:47:40,591 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_0cd325b0_uniq` UNIQUE (`group_id`, `permission_id`); (params [])
2016-05-16 14:47:40,648 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.056) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_0cd325b0_uniq` UNIQUE (`group_id`, `permission_id`); args=[]
2016-05-16 14:47:40,649 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
2016-05-16 14:47:40,744 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.095) ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); args=[]
2016-05-16 14:47:40,745 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
2016-05-16 14:47:40,849 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.104) ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); args=[]
2016-05-16 14:47:40,850 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_94350c0c_uniq` UNIQUE (`user_id`, `group_id`); (params [])
2016-05-16 14:47:40,908 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.057) ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_94350c0c_uniq` UNIQUE (`user_id`, `group_id`); args=[]
2016-05-16 14:47:40,909 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
2016-05-16 14:47:41,006 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.097) ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); args=[]
2016-05-16 14:47:41,007 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_perm_permission_id_1fbb5f2c_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
2016-05-16 14:47:41,114 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.106) ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_perm_permission_id_1fbb5f2c_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); args=[]
2016-05-16 14:47:41,115 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_14a6b632_uniq` UNIQUE (`user_id`, `permission_id`); (params [])
2016-05-16 14:47:41,166 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.051) ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_14a6b632_uniq` UNIQUE (`user_id`, `permission_id`); args=[]
2016-05-16 14:47:41,168 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:41,170 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0001_initial', '2016-05-16 14:47:41.169688'); args=['auth', '0001_initial', '2016-05-16 14:47:41.169688']
2016-05-16 14:47:41,201 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime(6) NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); (params None)
2016-05-16 14:47:41,241 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.040) CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime(6) NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); args=None
2016-05-16 14:47:41,243 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2016-05-16 14:47:41,243 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin__content_type_id_c4bce8eb_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
2016-05-16 14:47:41,339 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.095) ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin__content_type_id_c4bce8eb_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); args=[]
2016-05-16 14:47:41,339 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
2016-05-16 14:47:41,441 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.102) ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); args=[]
2016-05-16 14:47:41,443 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:41,444 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0001_initial', '2016-05-16 14:47:41.443952'); args=['admin', '0001_initial', '2016-05-16 14:47:41.443952']
2016-05-16 14:47:41,466 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ALTER COLUMN `action_time` SET DEFAULT %s; (params ['2016-05-16 14:47:41.466287'])
2016-05-16 14:47:41,474 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.007) ALTER TABLE `django_admin_log` ALTER COLUMN `action_time` SET DEFAULT '2016-05-16 14:47:41.466287'; args=['2016-05-16 14:47:41.466287']
2016-05-16 14:47:41,475 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ALTER COLUMN `action_time` DROP DEFAULT; (params [])
2016-05-16 14:47:41,481 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.006) ALTER TABLE `django_admin_log` ALTER COLUMN `action_time` DROP DEFAULT; args=[]
2016-05-16 14:47:41,483 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:41,485 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0002_logentry_remove_auto_add', '2016-05-16 14:47:41.483984'); args=['admin', '0002_logentry_remove_auto_add', '2016-05-16 14:47:41.483984']
2016-05-16 14:47:41,517 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; (params [])
2016-05-16 14:47:41,597 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.080) ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; args=[]
2016-05-16 14:47:41,608 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` DROP COLUMN `name` CASCADE; (params [])
2016-05-16 14:47:41,687 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.078) ALTER TABLE `django_content_type` DROP COLUMN `name` CASCADE; args=[]
2016-05-16 14:47:41,688 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:47:41,689 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('contenttypes', '0002_remove_content_type_name', '2016-05-16 14:47:41.688713'); args=['contenttypes', '0002_remove_content_type_name', '2016-05-16 14:47:41.688713']
2016-05-16 14:47:41,706 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; (params [])
2016-05-16 14:47:41,801 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.094) ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; args=[]
2016-05-16 14:47:41,802 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:41,803 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0002_alter_permission_name_max_length', '2016-05-16 14:47:41.803115'); args=['auth', '0002_alter_permission_name_max_length', '2016-05-16 14:47:41.803115']
2016-05-16 14:47:41,822 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user` MODIFY `email` varchar(254) NOT NULL; (params [])
2016-05-16 14:47:41,915 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.093) ALTER TABLE `auth_user` MODIFY `email` varchar(254) NOT NULL; args=[]
2016-05-16 14:47:41,917 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:41,919 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0003_alter_user_email_max_length', '2016-05-16 14:47:41.918223'); args=['auth', '0003_alter_user_email_max_length', '2016-05-16 14:47:41.918223']
2016-05-16 14:47:41,937 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:47:41,938 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0004_alter_user_username_opts', '2016-05-16 14:47:41.938087'); args=['auth', '0004_alter_user_username_opts', '2016-05-16 14:47:41.938087']
2016-05-16 14:47:41,955 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user` MODIFY `last_login` datetime(6) NULL; (params [])
2016-05-16 14:47:42,034 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.078) ALTER TABLE `auth_user` MODIFY `last_login` datetime(6) NULL; args=[]
2016-05-16 14:47:42,035 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:42,036 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0005_alter_user_last_login_null', '2016-05-16 14:47:42.036052'); args=['auth', '0005_alter_user_last_login_null', '2016-05-16 14:47:42.036052']
2016-05-16 14:47:42,043 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:47:42,045 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0006_require_contenttypes_0002', '2016-05-16 14:47:42.044417'); args=['auth', '0006_require_contenttypes_0002', '2016-05-16 14:47:42.044417']
2016-05-16 14:47:42,060 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:47:42,061 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0007_alter_validators_add_error_messages', '2016-05-16 14:47:42.061261'); args=['auth', '0007_alter_validators_add_error_messages', '2016-05-16 14:47:42.061261']
2016-05-16 14:47:42,070 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime(6) NOT NULL); (params None)
2016-05-16 14:47:42,109 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.039) CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime(6) NOT NULL); args=None
2016-05-16 14:47:42,110 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_session'; args=['django_session']
2016-05-16 14:47:42,111 [MainThread:140578974091008] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`); (params [])
2016-05-16 14:47:42,151 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.040) CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`); args=[]
2016-05-16 14:47:42,152 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:42,154 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('sessions', '0001_initial', '2016-05-16 14:47:42.153575'); args=['sessions', '0001_initial', '2016-05-16 14:47:42.153575']
2016-05-16 14:47:42,160 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:47:42,161 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:47:42,164 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'logentry' AND `django_content_type`.`app_label` = 'admin'); args=('logentry', 'admin')
2016-05-16 14:47:42,166 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'logentry' AND `django_content_type`.`app_label` = 'admin'); args=('logentry', 'admin')
2016-05-16 14:47:42,167 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('admin', 'logentry'); args=['admin', 'logentry']
2016-05-16 14:47:42,178 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.002) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (1) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
2016-05-16 14:47:42,180 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add log entry', 1, 'add_logentry'), ('Can change log entry', 1, 'change_logentry'), ('Can delete log entry', 1, 'delete_logentry'); args=('Can add log entry', 1, 'add_logentry', 'Can change log entry', 1, 'change_logentry', 'Can delete log entry', 1, 'delete_logentry')
2016-05-16 14:47:42,187 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'admin'; args=('admin',)
2016-05-16 14:47:42,189 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'permission' AND `django_content_type`.`app_label` = 'auth'); args=('permission', 'auth')
2016-05-16 14:47:42,190 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'permission' AND `django_content_type`.`app_label` = 'auth'); args=('permission', 'auth')
2016-05-16 14:47:42,191 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('auth', 'permission'); args=['auth', 'permission']
2016-05-16 14:47:42,203 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'group' AND `django_content_type`.`app_label` = 'auth'); args=('group', 'auth')
2016-05-16 14:47:42,204 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'group' AND `django_content_type`.`app_label` = 'auth'); args=('group', 'auth')
2016-05-16 14:47:42,205 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('auth', 'group'); args=['auth', 'group']
2016-05-16 14:47:42,213 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'auth'); args=('user', 'auth')
2016-05-16 14:47:42,215 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'auth'); args=('user', 'auth')
2016-05-16 14:47:42,218 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('auth', 'user'); args=['auth', 'user']
2016-05-16 14:47:42,226 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (2, 3, 4) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(2, 3, 4)
2016-05-16 14:47:42,227 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add permission', 2, 'add_permission'), ('Can change permission', 2, 'change_permission'), ('Can delete permission', 2, 'delete_permission'), ('Can add group', 3, 'add_group'), ('Can change group', 3, 'change_group'), ('Can delete group', 3, 'delete_group'), ('Can add user', 4, 'add_user'), ('Can change user', 4, 'change_user'), ('Can delete user', 4, 'delete_user'); args=('Can add permission', 2, 'add_permission', 'Can change permission', 2, 'change_permission', 'Can delete permission', 2, 'delete_permission', 'Can add group', 3, 'add_group', 'Can change group', 3, 'change_group', 'Can delete group', 3, 'delete_group', 'Can add user', 4, 'add_user', 'Can change user', 4, 'change_user', 'Can delete user', 4, 'delete_user')
2016-05-16 14:47:42,234 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'auth'; args=('auth',)
2016-05-16 14:47:42,237 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'contenttype' AND `django_content_type`.`app_label` = 'contenttypes'); args=('contenttype', 'contenttypes')
2016-05-16 14:47:42,238 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'contenttype' AND `django_content_type`.`app_label` = 'contenttypes'); args=('contenttype', 'contenttypes')
2016-05-16 14:47:42,239 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('contenttypes', 'contenttype'); args=['contenttypes', 'contenttype']
2016-05-16 14:47:42,247 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (5) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(5,)
2016-05-16 14:47:42,249 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add content type', 5, 'add_contenttype'), ('Can change content type', 5, 'change_contenttype'), ('Can delete content type', 5, 'delete_contenttype'); args=('Can add content type', 5, 'add_contenttype', 'Can change content type', 5, 'change_contenttype', 'Can delete content type', 5, 'delete_contenttype')
2016-05-16 14:47:42,255 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'contenttypes'; args=('contenttypes',)
2016-05-16 14:47:42,257 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'session' AND `django_content_type`.`app_label` = 'sessions'); args=('session', 'sessions')
2016-05-16 14:47:42,258 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'session' AND `django_content_type`.`app_label` = 'sessions'); args=('session', 'sessions')
2016-05-16 14:47:42,259 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('sessions', 'session'); args=['sessions', 'session']
2016-05-16 14:47:42,267 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (6) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(6,)
2016-05-16 14:47:42,269 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add session', 6, 'add_session'), ('Can change session', 6, 'change_session'), ('Can delete session', 6, 'delete_session'); args=('Can add session', 6, 'add_session', 'Can change session', 6, 'change_session', 'Can delete session', 6, 'delete_session')
2016-05-16 14:47:42,275 [MainThread:140578974091008] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'sessions'; args=('sessions',)
2016-05-16 14:47:47,024 [Dummy-1:140714095929088] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:47:47,050 [Dummy-1:140714095929088] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:47:47,051 [Dummy-1:140714095929088] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:47:47,054 [Dummy-1:140714095929088] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:48:07,048 [MainThread:140508646819584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:48:15,015 [Dummy-1:140555895981824] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:48:15,043 [Dummy-1:140555895981824] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:48:15,044 [Dummy-1:140555895981824] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:48:15,046 [Dummy-1:140555895981824] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:48:57,689 [Thread-2:140555884652288] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in "[{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd5b796ed08>>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7fd5b799eea0>>, 'request': <WSGIRequest: GET '/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fd5b796f320>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'SUCCESS': 25, 'INFO': 20, 'DEBUG': 10, 'ERROR': 40}, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd5b4904da0>}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-05-16 14:48:57,690 [Thread-2:140555884652288] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in "[{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd5b796ed08>>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7fd5b799eea0>>, 'request': <WSGIRequest: GET '/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fd5b796f320>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'SUCCESS': 25, 'INFO': 20, 'DEBUG': 10, 'ERROR': 40}, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd5b4904da0>}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-05-16 14:50:00,075 [Dummy-1:139803015096064] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:50:00,099 [Dummy-1:139803015096064] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:50:00,099 [Dummy-1:139803015096064] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:50:00,102 [Dummy-1:139803015096064] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:50:48,349 [Dummy-1:140234352985856] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:50:48,367 [Dummy-1:139815557089024] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:50:48,379 [Dummy-1:140234352985856] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:50:48,380 [Dummy-1:140234352985856] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:50:48,383 [Dummy-1:140234352985856] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:50:48,394 [Dummy-1:139815557089024] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:50:48,395 [Dummy-1:139815557089024] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:50:48,398 [Dummy-1:139815557089024] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:51:12,240 [Dummy-1:140682626979584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:51:12,266 [Dummy-1:140682626979584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:51:12,267 [Dummy-1:140682626979584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:51:12,269 [Dummy-1:140682626979584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:51:20,315 [Dummy-1:140228523878144] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:51:20,357 [Dummy-1:140228523878144] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:51:20,358 [Dummy-1:140228523878144] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:51:20,360 [Dummy-1:140228523878144] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:52:14,534 [Dummy-1:140031257884416] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:52:14,558 [Dummy-1:140031257884416] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:52:14,558 [Dummy-1:140031257884416] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:52:14,560 [Dummy-1:140031257884416] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:52:14,696 [Dummy-1:139905546155776] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:52:14,730 [Dummy-1:139905546155776] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:52:14,731 [Dummy-1:139905546155776] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:52:14,734 [Dummy-1:139905546155776] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:52:17,492 [Dummy-1:140571229087488] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:52:17,515 [Dummy-1:140571229087488] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:52:17,515 [Dummy-1:140571229087488] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2016-05-16 14:52:17,518 [Dummy-1:140571229087488] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:55:26,525 [MainThread:140289723856640] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:56:01,286 [MainThread:139728329656064] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:56:05,076 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:56:05,110 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:56:05,112 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:56:05,115 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:56:05,117 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-05-16 14:56:05,118 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-05-16 14:56:05,151 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'logentry' AND `django_content_type`.`app_label` = 'admin'); args=('logentry', 'admin')
2016-05-16 14:56:05,154 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (1) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
2016-05-16 14:56:05,155 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'admin'; args=('admin',)
2016-05-16 14:56:05,157 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'permission' AND `django_content_type`.`app_label` = 'auth'); args=('permission', 'auth')
2016-05-16 14:56:05,159 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'group' AND `django_content_type`.`app_label` = 'auth'); args=('group', 'auth')
2016-05-16 14:56:05,160 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'auth'); args=('user', 'auth')
2016-05-16 14:56:05,163 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (2, 3, 4) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(2, 3, 4)
2016-05-16 14:56:05,164 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'auth'; args=('auth',)
2016-05-16 14:56:05,166 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'contenttype' AND `django_content_type`.`app_label` = 'contenttypes'); args=('contenttype', 'contenttypes')
2016-05-16 14:56:05,169 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (5) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(5,)
2016-05-16 14:56:05,171 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'contenttypes'; args=('contenttypes',)
2016-05-16 14:56:05,174 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'session' AND `django_content_type`.`app_label` = 'sessions'); args=('session', 'sessions')
2016-05-16 14:56:05,177 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (6) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(6,)
2016-05-16 14:56:05,178 [MainThread:139785968965376] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'sessions'; args=('sessions',)
2016-05-16 14:57:02,433 [Thread-12:140570982868736] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:57:02,439 [Thread-12:140570982868736] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:57:02,440 [Thread-12:140570982868736] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'w5vcdu6rlvjrjp2kzu1x19nyza4u3v6n' AND `django_session`.`expire_date` > '2016-05-16 14:57:02.430066'); args=('w5vcdu6rlvjrjp2kzu1x19nyza4u3v6n', '2016-05-16 14:57:02.430066')
2016-05-16 14:57:02,471 [Thread-13:140570966083328] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'SITE_NAME': 'Zack的个人博客', 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd9487da358>, 'SITE_DESC': '专注Python开发，欢迎和大家交流', 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fd94a32c5c0>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd949815730>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fd949861cf8>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'ERROR': 40, 'SUCCESS': 25, 'DEBUG': 10, 'INFO': 20}}, {}, {'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'site_url': '/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1d30>, 'app_path': '/admin/login/?next=/admin/', 'site': <django.contrib.sites.requests.RequestSite object at 0x7fd9487f0278>, 'site_name': 'localhost:8000', 'available_apps': [], 'has_permission': False, 'LANGUAGE_CODE': 'en-us', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1c88>, 'next': '/admin/', 'LANGUAGE_BIDI': False, 'title': 'Log in'}]"
2016-05-16 14:57:02,474 [Thread-13:140570966083328] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'SITE_NAME': 'Zack的个人博客', 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd9487da358>, 'SITE_DESC': '专注Python开发，欢迎和大家交流', 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fd94a32c5c0>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd949815730>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fd949861cf8>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'ERROR': 40, 'SUCCESS': 25, 'DEBUG': 10, 'INFO': 20}}, {}, {'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'site_url': '/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1d30>, 'app_path': '/admin/login/?next=/admin/', 'site': <django.contrib.sites.requests.RequestSite object at 0x7fd9487f0278>, 'site_name': 'localhost:8000', 'available_apps': [], 'has_permission': False, 'LANGUAGE_CODE': 'en-us', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1c88>, 'next': '/admin/', 'LANGUAGE_BIDI': False, 'title': 'Log in'}]"
2016-05-16 14:57:04,166 [Thread-14:140571217757952] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:57:04,170 [Thread-14:140571217757952] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-05-16 14:57:04,171 [Thread-14:140571217757952] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'haohao'; args=('haohao',)
2016-05-16 14:57:04,215 [Thread-14:140571217757952] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'SITE_NAME': 'Zack的个人博客', 'request': <WSGIRequest: POST '/admin/login/?next=/admin/'>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd94877c9e8>, 'SITE_DESC': '专注Python开发，欢迎和大家交流', 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fd9487681d0>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd948785c80>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fd9487682b0>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'ERROR': 40, 'SUCCESS': 25, 'DEBUG': 10, 'INFO': 20}}, {}, {'form': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, 'site_url': '/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1d30>, 'app_path': '/admin/login/?next=/admin/', 'site': <django.contrib.sites.requests.RequestSite object at 0x7fd94dd33940>, 'site_name': 'localhost:8000', 'available_apps': [], 'has_permission': False, 'LANGUAGE_CODE': 'en-us', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1c88>, 'next': '/admin/', 'LANGUAGE_BIDI': False, 'title': 'Log in'}]"
2016-05-16 14:57:04,216 [Thread-14:140571217757952] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'SITE_NAME': 'Zack的个人博客', 'request': <WSGIRequest: POST '/admin/login/?next=/admin/'>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd94877c9e8>, 'SITE_DESC': '专注Python开发，欢迎和大家交流', 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fd9487681d0>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd948785c80>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fd9487682b0>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'ERROR': 40, 'SUCCESS': 25, 'DEBUG': 10, 'INFO': 20}}, {}, {'form': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, 'site_url': '/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1d30>, 'app_path': '/admin/login/?next=/admin/', 'site': <django.contrib.sites.requests.RequestSite object at 0x7fd94dd33940>, 'site_name': 'localhost:8000', 'available_apps': [], 'has_permission': False, 'LANGUAGE_CODE': 'en-us', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1c88>, 'next': '/admin/', 'LANGUAGE_BIDI': False, 'title': 'Log in'}]"
2016-05-16 14:57:06,654 [Thread-16:140571209365248] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'SITE_NAME': 'Zack的个人博客', 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd948798978>, 'SITE_DESC': '专注Python开发，欢迎和大家交流', 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fd94982bef0>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd9487dc6a8>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fd94982bf60>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'ERROR': 40, 'SUCCESS': 25, 'DEBUG': 10, 'INFO': 20}}, {}, {'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'site_url': '/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1d30>, 'app_path': '/admin/login/?next=/admin/', 'site': <django.contrib.sites.requests.RequestSite object at 0x7fd94a318ef0>, 'site_name': 'localhost:8000', 'available_apps': [], 'has_permission': False, 'LANGUAGE_CODE': 'en-us', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1c88>, 'next': '/admin/', 'LANGUAGE_BIDI': False, 'title': 'Log in'}]"
2016-05-16 14:57:06,654 [Thread-16:140571209365248] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.4/dist-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'None': None, 'False': False}, {'SITE_NAME': 'Zack的个人博客', 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd948798978>, 'SITE_DESC': '专注Python开发，欢迎和大家交流', 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fd94982bef0>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd9487dc6a8>>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fd94982bf60>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'ERROR': 40, 'SUCCESS': 25, 'DEBUG': 10, 'INFO': 20}}, {}, {'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'site_url': '/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1d30>, 'app_path': '/admin/login/?next=/admin/', 'site': <django.contrib.sites.requests.RequestSite object at 0x7fd94a318ef0>, 'site_name': 'localhost:8000', 'available_apps': [], 'has_permission': False, 'LANGUAGE_CODE': 'en-us', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x7fd94b2f1c88>, 'next': '/admin/', 'LANGUAGE_BIDI': False, 'title': 'Log in'}]"
